Feature/perodic canister
staex-io/vts pull request #25
Opened 2024-06-13 22:30 UTC by Robka99

2024-06-14 15:17 UTC, lavrd requested changes

2024-06-14 15:17 UTC, lavrd commented on canisters/src/vts/src/lib.rs
> +#[derive(BEncode, BDecode, Debug, PartialEq, Eq, CandidType, Deserialize, Clone, Default)]
BEncode and BDecode are not needed here, we do not send these types through TCP API.

2024-06-14 15:17 UTC, lavrd commented on canisters/src/vts/src/lib.rs
> +
Let's remove this newline :)

2024-06-14 15:17 UTC, lavrd commented on canisters/src/vts/src/lib.rs
> +fn get_aggregated_telemetry(vehicle: Principal) -> VTSResult<AggregatedTelemetry> {
Let's pass here interval. Like make a enum { Daily, Weekly, Monthly }.

2024-06-16 19:41 UTC, Robka99 commented on canisters/src/vts/src/lib.rs
> +}
@lavrd enum interval like this?

2024-06-18 09:57 UTC, lavrd requested changes
Update after #26

2024-06-21 06:09 UTC, lavrd requested changes
So as we have a method to pre-fill data for the canister. Can we use this method in tests and write a test that telemetry aggregation is working properly? I think we can implement separate canister method to accumulate data and use it in test to not wait timer, for example. And in timer method we can use it to not write this logic twice.

2024-06-21 10:23 UTC, Robka99 commented
> So as we have a method to pre-fill data for the canister. Can we use this method in tests and write a test that telemetry aggregation is working properly? I think we can implement separate canister method to accumulate data and use it in test to not wait timer, for example. And in timer method we can use it to not write this logic twice.

maybe we can use a method like this for testing:
```
fn accumulate_telemetry_data_now() -> Result<(), Error> {
    accumulate_telemetry_data()
}
```
so we dont have to wait for the timer.

in the test class we can use: `fill_predefined_telemetry()` and `accumulate_telemetry_data_now()`

2024-06-21 13:11 UTC, lavrd commented
> > So as we have a method to pre-fill data for the canister. Can we use this method in tests and write a test that telemetry aggregation is working properly? I think we can implement separate canister method to accumulate data and use it in test to not wait timer, for example. And in timer method we can use it to not write this logic twice.
> 
> 
> 
> maybe we can use a method like this for testing:
> 
> ```
> 
> fn accumulate_telemetry_data_now() -> Result<(), Error> {
> 
>     accumulate_telemetry_data()
> 
> }
> 
> ```
> 
> so we dont have to wait for the timer.
> 
> 
> 
> in the test class we can use: `fill_predefined_telemetry()` and `accumulate_telemetry_data_now()`
> 
> 

Yea, sure)

2024-06-24 13:59 UTC, lavrd approved these changes

2024-06-24 13:59 UTC, merged